'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, Check, CheckCheck, GripVertical, Users, Zap } from 'lucide-react';
import { useSession, errorMessage } from '@/components/providers';
import { Header, Footer, ErrorNotice } from '@/components/ui';
export default function Home() {
  const { user, login, loading } = useSession(); const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (user) router.replace('/boards'); }, [user, router]);
  return <><Header /><main className="landing"><section className="hero-copy"><span className="eyebrow"><span className="tiny-square" /> LESS BUSY. MORE DONE.</span><h1>A little space<br />for <span className="highlight">progress.</span></h1><p>Clear your head. Gather your people.<br />Turn your to-dos into done, one card at a time.</p><button className="button hero-button" disabled={busy || loading} onClick={async () => { setBusy(true); setError(''); try { await login(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }}><svg width="19" height="19" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M21.8 12.2c0-.7-.1-1.4-.2-2.1H12v4h5.5a4.7 4.7 0 0 1-2 3.1v2.6h3.3c1.9-1.8 3-4.4 3-7.6ZM12 22c2.7 0 5-.9 6.7-2.5l-3.3-2.6c-.9.6-2 1-3.4 1-2.6 0-4.9-1.8-5.7-4.2H2.9v2.7A10 10 0 0 0 12 22ZM6.3 13.7A6 6 0 0 1 6 12c0-.6.1-1.2.3-1.7V7.6H2.9A10 10 0 0 0 2 12c0 1.6.4 3.1.9 4.4l3.4-2.7ZM12 6.1c1.5 0 2.8.5 3.8 1.5l2.9-2.9A9.6 9.6 0 0 0 12 2a10 10 0 0 0-9.1 5.6l3.4 2.7C7.1 7.9 9.4 6.1 12 6.1Z" /></svg>{busy ? 'Opening Google…' : 'Continue with Google'}<ArrowRight size={18} /></button><ErrorNotice message={error} /><span className="hero-note"><Check size={14} /> Free to start. Refreshingly simple.</span></section><section className="hero-preview" aria-label="Example task board"><div className="preview-header"><span><span className="tiny-square" /> THE NEXT BIG THING</span><span className="pill">Your workspace</span></div><div className="preview-columns">{[{ name: 'To do', tasks: ['The idea that won’t leave your head', 'Make a little room for it'] }, { name: 'In progress', tasks: ['Start somewhere'] }, { name: 'Done', tasks: ['Take the first step'] }].map((col, i) => <div className="preview-column" key={col.name}><div className="column-title"><span className={`status-dot status-${i}`} />{col.name}<span className="count">{col.tasks.length}</span></div>{col.tasks.map((task, j) => <div className={`preview-card ${i === 1 ? 'featured-card' : ''}`} key={task}>{i === 1 && <span className="small-label">ONE THING AT A TIME</span>}<span>{task}</span><div className="preview-card-bottom">{i === 2 ? <CheckCheck size={16} /> : <GripVertical size={14} />}<span className="mini-avatar">{i === 1 ? 'Y' : 'T'}</span></div>{i === 0 && j === 0 && <span className="priority priority-high">High priority</span>}</div>)}</div>)}</div><div className="preview-caption"><span className="live-dot" /> A clearer picture of what’s next.</div></section><section className="landing-features"><div><span className="feature-icon"><GripVertical size={20} /></span><h2>Find your flow.</h2><p>Simple boards that move with you.</p></div><div><span className="feature-icon"><Users size={20} /></span><h2>Bring your people.</h2><p>A shared space. A little less back-and-forth.</p></div><div><span className="feature-icon"><Zap size={20} /></span><h2>Keep it light.</h2><p>Just what you need to get things done.</p></div></section></main><Footer /></>;
}
